### ISSUE TITLE
dashboard - maintenance - buttons stacking

### ISSUE THREAD

**Issue by rhukster** [Vivalldi/grav-plugin-admin#3]
at a certain size, the buttons stack, this looks a bit ugly:

![2015-09-01-12-r05a1](https://cloud.githubusercontent.com/assets/1084697/9613322/dc267dbe-50a7-11e5-97a5-55299282a2c3.png)

Could remove some padding on all buttons in this mediaquery size:

![2015-09-01-12-n94de](https://cloud.githubusercontent.com/assets/1084697/9613351/0b0330c8-50a8-11e5-8346-9de3337dbd42.png)

**Comment by Vivalldi** [comment]
Tablet sized buttons no longer stack
