### ISSUE TITLE
mobile - sidenav - close needed

### ISSUE THREAD

**Issue by rhukster** [Vivalldi/grav-plugin-admin#4]
Currently there is no way to close the menu without clicking on something:

![2015-09-01-12-q82lb](https://cloud.githubusercontent.com/assets/1084697/9613379/39a0bfd6-50a8-11e5-8167-b3ed8886d5c2.png)

**Comment by Vivalldi** [comment]
As of right now you can click the background. Button capability coming.

**Comment by rhukster** [comment]
as in gitter, maybe look at learn2 (learn.getgrav.org) in mobile, it is 75% or so wide, so you can click on content to close..

Right now, i close clicking below, but it opens again straight away..

**Comment by Vivalldi** [comment]
Menu is fixed.
